namespace Sefer.Backend.Authentication.Lib.Cryptography;

/// <summary>
/// Ease implementation of the time protect query string by provided a model that can be implemented
/// </summary>
public interface ITimeProtectedModel
{
    /// <summary>
    /// The Data with encrypted information
    /// </summary>
    string Data { get; }

    /// <summary>
    /// Random stuff acting as an second salt
    /// </summary>
    string Random { get; }

    /// <summary>
    /// The date the url was generated
    /// </summary>
    string Date { get; }

    /// <summary>
    /// The hash to prove the url is generated by the back-end
    /// </summary>
    string Hash { get; }
}
